module.exports = [
    "Adjetivo",
    "Ator",
    "Animal",
    "App ou site",
    "Banda",
    "Capital",
    "Cantor",
    "Carro",
    "Comida",
    "CEP",
    "Celebridade",
    "Cidade",
    "Cor",
    "Desenho animado",
    "Eletro Eletrônico",
    "Esporte",
    "Esportista",
    "Gentílico",
    "Filme",
    "Flor",
    "FLV",
    "Fruta",
    "Game",
    "Inseto",
    "Instrumento Musical",
    "JLR",
    "Líquido",
    "Marca",
    "Música",
    "MSÉ",
    "Nome Feminino",
    "Nome Masculino",
    "Objeto",
    "Profissão",
    "País",
    "Palavra em inglês",
    "PCH",
    "PDA",
    "Personagem Fictício",
    "Programa de TV",
    "Série",
    "Sobremesa",
    "Sobrenome",
    "Time esportivo",
    "Verbo",
    "Vestuário"
];